steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - composer
  - environments
  - storage
  - dags
  - import
  - --environment=${_COMPOSER_ENV}
  - --location=${_LOCATION}
  - --source=.

substitutions:
  _COMPOSER_ENV: 'pairs-trading-orchestrator'
  _LOCATION: 'europe-west4'

options:
  logging: CLOUD_LOGGING_ONLY