steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - composer
  - environments
  - storage
  - dags
  - import
  - --environment=${_COMPOSER_ENV}
  - --location=${_LOCATION}
  - --source=dags

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - composer
  - environments
  - storage
  - plugins
  - import
  - --environment=${_COMPOSER_ENV}
  - --location=${_LOCATION}
  - --source=plugins

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - composer
  - environments
  - storage
  - data
  - import
  - --environment=${_COMPOSER_ENV}
  - --location=${_LOCATION}
  - --source=requirements.txt
  - --destination=requirements.txt

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud composer environments run ${_COMPOSER_ENV} \
      --location=${_LOCATION} \
      pip install -r /home/airflow/gcs/data/requirements.txt

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - composer
  - environments
  - restart
  - workers
  - ${_COMPOSER_ENV}
  - --location=${_LOCATION}

substitutions:
  _COMPOSER_ENV: 'pairs-trading-orchestrator'
  _LOCATION: 'europe-west4'

options:
  logging: CLOUD_LOGGING_ONLY