steps:
# Deploy DAGs to Composer
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy DAGs'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    DAGS_BUCKET=$(gcloud composer environments describe ${_COMPOSER_ENV} \
      --location ${_LOCATION} \
      --format="value(config.dagGcsPrefix)")
    
    # Extract just the bucket name if it's a full GCS path
    BUCKET_NAME=$(echo $DAGS_BUCKET | sed 's|gs://\([^/]*\).*|\1|')
    
    echo "Deploying DAGs to bucket: $BUCKET_NAME"
    
    if gsutil -m rsync -d -r ./dags gs://$BUCKET_NAME/dags; then
      echo "Successfully deployed DAGs to Composer"
    else
      echo "Failed to deploy DAGs to Composer"
      exit 1
    fi

substitutions:
  _COMPOSER_ENV: 'pairs-trading-orchestrator'
  _LOCATION: 'europe-west4'

options:
  logging: CLOUD_LOGGING_ONLY